"""empty message

Revision ID: 10d66bb5392e
Revises: None
Create Date: 2015-01-03 01:06:20.677463

"""

# revision identifiers, used by Alembic.
revision = '10d66bb5392e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('best_friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['best_friend_id'], ['monkeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monkeys_name'), 'monkeys', ['name'], unique=False)
    op.create_table('friends',
    sa.Column('monkey_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['monkeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monkey_id'], ['monkeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monkey_id', 'friend_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    op.drop_index(op.f('ix_monkeys_name'), table_name='monkeys')
    op.drop_table('monkeys')
    ### end Alembic commands ###
