"""empty message

Revision ID: f67a9b8459d
Revises: 10d66bb5392e
Create Date: 2015-01-06 23:38:59.524326

"""

# revision identifiers, used by Alembic.
revision = 'f67a9b8459d'
down_revision = '10d66bb5392e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monkeys', sa.Column('friends_count', sa.Integer(), nullable=True))
    op.create_index('ix_monkey_fCount_id', 'monkeys', ['friends_count', 'id'], unique=True)
    op.create_index('ix_monkey_name_id', 'monkeys', ['name', 'id'], unique=True)
    op.create_index(op.f('ix_monkeys_best_friend_id'), 'monkeys', ['best_friend_id'], unique=False)
    op.drop_index('ix_monkeys_name', table_name='monkeys')
    op.execute("""UPDATE monkeys SET friends_count =
        (SELECT COUNT(*) FROM friends WHERE monkey_id = monkeys.id)""")
    op.execute(sa.DDL("""
    CREATE OR REPLACE FUNCTION process_change_monkey_friends_count()
    RETURNS TRIGGER AS $change_monkey_friends_count$
        BEGIN
            IF (TG_OP = 'DELETE') THEN
                UPDATE monkeys SET friends_count = friends_count - 1
                    WHERE id = OLD.monkey_id;
                RETURN OLD;
            ELSIF (TG_OP = 'INSERT') THEN
                UPDATE monkeys SET friends_count = friends_count + 1
                    WHERE id = NEW.monkey_id;
                RETURN NEW;
            END IF;
            RETURN NULL;
        END;
    $change_monkey_friends_count$ LANGUAGE plpgsql;

    CREATE TRIGGER change_monkey_friends_count
    AFTER INSERT OR DELETE ON friends
        FOR EACH ROW EXECUTE PROCEDURE process_change_monkey_friends_count();
    """))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.DDL("""
    DROP TRIGGER change_monkey_friends_count ON friends;
    DROP FUNCTION process_change_monkey_friends_count();
    """))
    op.create_index('ix_monkeys_name', 'monkeys', ['name'], unique=False)
    op.drop_index(op.f('ix_monkeys_best_friend_id'), table_name='monkeys')
    op.drop_index('ix_monkey_name_id', table_name='monkeys')
    op.drop_index('ix_monkey_fCount_id', table_name='monkeys')
    op.drop_column('monkeys', 'friends_count')
    ### end Alembic commands ###
